config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # 被りそうだから変更
    path('admin/admin/', admin.site.urls),
    path('', include('history.urls')),
]

history/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('list/<str:username>/', views.HistoryListView.as_view(), name='list'),
    path('detailhis/<int:pk>', views.HistoryDetailView.as_view(), name='detail_his'),
    path('createhis/', views.HistoryCreateView.as_view(), name='create_his'),
    path('createtag/', views.TagCreateView.as_view(), name='create_tag'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logoutfunc, name='logout'),
    path('update/<int:pk>', views.HistroyUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.HistoryDeleteView.as_view(), name='delete'),
    path('search_user', views.SearchUserView.as_view(), name='search_user')
]

history/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in

# Create your models here.


class CustomUserModel(AbstractUser):
    '''カスタムユーザークラス'''
    class Meta(object):
        db_table = 'custom_user'
    university = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.username


class TagModel(models.Model):
    '''タグモデル'''
    tag_name = models.CharField(verbose_name='タグ名', max_length=255)
    username = models.ForeignKey(CustomUserModel, to_field='username', on_delete=models.CASCADE)

    def __str__(self):
        return self.tag_name


class HistoryModel(models.Model):
    '''メインモデル，質問と回答を蓄積'''
    class Meta(object):
        db_table = 'history_table'

    # 質問
    question = models.TextField(verbose_name='質問')
    answer = models.TextField(verbose_name='回答')
    create_date = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    tags = models.ManyToManyField(TagModel, verbose_name='タグ名', blank=True)

    OPEN_INFO_CHOICES = [
        ('public', '公開'),
        ('private', '非公開')
    ]
    open_info = models.CharField(verbose_name='公開', max_length=20,
                                 choices=OPEN_INFO_CHOICES, default='private')
    company = models.CharField(verbose_name='会社名', max_length=50, blank=True, null=True)
    state = models.CharField(verbose_name='状況', max_length=50, blank=True, null=True)
    username = models.ForeignKey(CustomUserModel, to_field='username',
                                 verbose_name='ユーザ名', on_delete=models.CASCADE)
    char_num = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.question

history/forms.py
from django import forms
from .models import HistoryModel, TagModel


class HistoryCreateForm(forms.ModelForm):
    '''ポストを作成するフォーム'''
    class Meta:
        model = HistoryModel
        fields = ('question', 'answer', 'tags', 'open_info',
                  'company', 'state', 'username', 'char_num')


class TagCreateForm(forms.ModelForm):
    '''タグを作成するフォームクラス'''
    class Meta:
        model = TagModel
        fields = ('tag_name', 'username')


class UpdateForm(forms.ModelForm):
    '''ポストを修正するフォーム'''
    class Meta:
        model = HistoryModel
        fields = ('question', 'answer', 'tags', 'open_info',
                  'company', 'state')

history/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, DeleteView, UpdateView
from .models import CustomUserModel, TagModel, HistoryModel
from django.urls import reverse_lazy, reverse
from django.views import View
from .forms import HistoryCreateForm, TagCreateForm, UpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

# Create your views here.


class SignupView(View):
    '''サインアップ'''

    def get(self, request, *args, **kwargs):
        return render(request, 'history/signup.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']

        # ユーザーを追加
        if CustomUserModel.objects.filter(username=username).exists():
            return render(request, 'history/signup.html', {'error': 'このユーザー名は既に登録されています．'})
        else:
            CustomUserModel.objects.create_user(username, '', password)
            return redirect('login')


class LoginView(View):
    '''ログイン'''

    def get(self, request, *args, **kwargs):
        return render(request, 'history/login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('list', username=username)
        else:
            return redirect('login')

# ログアウト関数


def logoutfunc(request):
    logout(request)
    return redirect('login')


class HistoryCreateView(View):
    '''質問と回答(post)を作成する'''

    def get(self, request, *args, **kwargs):
        login_username = request.user.username
        tags = TagModel.objects.filter(username=login_username)
        num_tags = len(tags)

        # ポスト作成画面(templates/history/create_post.html)にて一度に表示するタグ数の上限
        # タグの数が上限より多い時はスクロールになる
        max_num_tags = 10
        context = {
            'form': HistoryCreateForm(),
            'login_username': login_username,
            'tags': tags,
            # タグの数に応じてpost画面のタグの表示数を変更
            'len_tags': min(num_tags, max_num_tags),
        }
        return render(request, 'history/create_post.html', context)

    def post(self, request, *args, **kwargs):
        login_username = request.user.username

        # 回答の文字数を取得
        # 回答の前後にスペースがある場合，それらを削除してから文字数を取得
        request_copy = request.POST.copy()
        request_copy['question'] = request_copy['question'].rstrip().lstrip()
        request_copy['answer'] = request_copy['answer'].rstrip().lstrip()
        request_copy['char_num'] = len(request_copy['answer'])
        form = HistoryCreateForm(request_copy)
        if form.is_valid():
            form.save()
            print('ok')
            return redirect('list', username=login_username)
        else:
            print('failed')
            return redirect('create_his')


# class Userlist(ListView):
#     model = HistoryModel
#     slug_field = "username"
#     slug_url_kwarg = "username"
#     template_name = 'history/list.html'

#     def get_object(self):
#         object = get_object_or_404(HistoryModel, username=self.kwargs.get("username"))
#         if self.request.user.username == object.username:
#             return object
#         else:
#             print("you are not the owner!!")


class HistoryListView(ListView):
    # memo LoginRequiredMixinとListViewの順番を入れ替えるとうまくいかない
    '''タスクの一覧を表示'''

    def get(self, request, username):
        # ログイン中のユーザー名を取得
        login_username = request.user.username
        if login_username == '':
            login_username = 'ゲスト'

        # print('---------------')
        # print(login_username)
        # print(type(login_username))
        # print(len(login_username))
        # print('---------------')

        # ゆーざーDBに登録されていないユーザ名がリクエストされることも想定される
        # この方法がベストかはわからないがとりあえず．
        # ユーザーが存在していないときの処理
        if CustomUserModel.objects.filter(username=username).count() == 0:
            context = {
                'username': username,
                'login_username': login_username,
            }
            return render(request, 'history/list_not_exist.html', context)

        # ログインしていない人のポストを見るときには制限をかける
        # ログインしているとき
        if login_username == username:
            histories = HistoryModel.objects.filter(username=username)

            context = {
                'username': username,
                'histories': histories,
                'login_username': login_username
            }
            return render(request, 'history/list.html', context)

        # ログインしていないとき
        else:
            # memo:カンマで区切るとAND検索
            histories = HistoryModel.objects.filter(username=username, open_info='public')
            context = {
                'username': username,
                'histories': histories,
                'login_username': login_username,
            }
            return render(request, 'history/list_not_login.html', context)


class HistoryDetailView(DetailView):
    '''タスクの詳細を表示'''
    template_name = 'history/detail_his.html'
    model = HistoryModel


class HistoryDeleteView(DeleteView):
    '''タスクを削除'''

    template_name = 'history/delete_post.html'
    model = HistoryModel
    # success_url = reverse_lazy('list', username=login_username)

    def get_success_url(self):
        print(self.request.user.username)
        return reverse('list', kwargs={'username': self.request.user.username})


class HistroyUpdateView(View):
    '''ポストを修正'''

    def get(self, request, pk, *args, **kwargs):
        login_username = request.user.username
        post = HistoryModel.objects.get(pk=pk)
        form = UpdateForm(instance=post)
        tags = TagModel.objects.filter(username=login_username)
        print(post)
        context = {
            'form': form,
            'login_username': login_username,
            'tags': tags,
            # タグの数に応じてpost画面のタグの表示数を変更，タグが10個以上の場合はスクロール
            'len_tags': min(len(tags), 10),
        }
        return render(request, 'history/update_post.html', context)

    def post(self, request, pk, *args, **kwargs):
        login_username = request.user.username
        post = HistoryModel.objects.get(pk=pk)
        form = UpdateForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('list', username=login_username)
        else:
            return redirect('update')


class TagCreateView(View):
    '''タグを作成するview'''

    def get(self, request, *args, **kwargs):
        login_username = request.user.username
        tags = TagModel.objects.filter(username=login_username)
        num_tags = len(tags)
        context = {
            'form': TagCreateForm(),
            'login_username': login_username,
            'tags': tags,
            'num_tags': num_tags,
        }
        return render(request, 'history/create_tag.html', context)

    def post(self, request, *args, **kwargs):
        login_username = request.user.username
        form = TagCreateForm(request.POST)
        if form.is_valid():
            form.save()
            print('ok')
            return redirect('list', username=login_username)
        else:
            print('failed')
            return redirect('create_tag')


class SearchUserView(View):
    '''ユーザー検索'''

    def get(self, request, *args, **kwargs):
        search_user = self.request.GET.get('search_username')
        login_username = request.user.username
        if login_username == '':
            login_username = 'ゲスト'
        context = {
            'login_username': login_username,
            'search_user': search_user,
        }
        if CustomUserModel.objects.filter(username=search_user).exists():
            context['error'] = False
        else:
            context['error'] = True
        return render(request, 'history/search_user.html', context)

templates/history/create_post.html
{% extends 'base.html' %}


{% block header %}
<div class="alert alert-secondary" role="alert">
    <div class="container">
        <p class="display-4">新しい質問を追加</p>
    </div>
</div>

{% endblock header %}


{% block content %}
<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        <p>質問</p>
        <p>{{form.question}}</p>
        <p>回答</p>
        <p>{{form.answer}}</p>
        <p>タグ(複数選択できます(ctrlまたはcmmd+クリック))</p>

        {% if len_tags == 0 %}
        <div class="box">
            <p>タグはまだありません</p>
        </div>

        {% else %}
        <p><label for="id_tags"></label> <select size="{{len_tags}}" name="tags" id="id_tags" multiple>

                {% for tag in tags %}
                <option value="{{tag.pk}}">{{tag.tag_name}}</option>
                {% endfor %}

            </select></p>
        {% endif %}


        <p>企業名{{form.company}}</p>
        <p>イベント{{form.state}}</p>
        <p>公開{{form.open_info}}</p>

        <input type="hidden" name=username value="{{login_username}}">
        <input type="submit" value="作成する">
    </form>
</div>

{% endblock content %}

templates/history/create_tag.html
{% extends 'base.html' %}


{% block header %}
<div class="alert alert-secondary" role="alert">
    <div class="container">
        <p class="display-4">新しいタグを追加</p>

        {% if num_tags == 0 %}
        <p>まだタグはありません</p>
        {% else %}
        <p>既存のタグ(同じ名前のタグは作成できません)</p>
        {% for tag in tags %}
        <a href="#" class="btn btn-dark btn" tabindex="-1" role="button" aria-disabled="true">{{tag}}</a>
        {% endfor %}
        {% endif %}
    </div>
</div>

{% endblock header %}


{% block content %}
<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        <p>タグ名</p>
        <p>{{form.tag_name}}</p>
        <input type="hidden" name=username value="{{login_username}}">
        <input type="submit" value="作成する">
    </form>
</div>

{% endblock content %}

templates/history/delete_post.html
<!doctype html>
{% load static %}
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'history/delete_post.css' %}">
    <title>ES質問まとめアプリ</title>

</head>

<body>
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">本当に削除しますか？</h1>
            <p class="lead">削除しない場合はブラウザバックしてください</p>
            <form action="" method="POST">{% csrf_token %}
                <input type="submit" value="削除します">
            </form>
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/history/detail_his.html
<!doctype html>
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>ES質問まとめアプリ</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{%url 'list' object.username%}">ES質問まとめアプリ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="navbar-brand">{{object.username}}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'create_his' %}">質問を追加<span class="sr-only">(current)</span></a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'logout' %}">ログアウト<span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">詳細画面</h1>
            <a href="{% url 'list' object.username %}" class="btn btn-warning btn-lg" tabindex="-1" role="button"
                aria-disabled="true">一覧に戻る</a>
            <br>
            <br>
            <a href="{% url 'update' object.pk%}" class="btn btn-primary btn" tabindex="-1" role="button"
                aria-disabled="true">編集</a>
            <a href="{% url 'delete' object.pk%}" class="btn btn-danger btn" tabindex="-1" role="button"
                aria-disabled="true">削除</a>
        </div>
    </div>

    <div class="container">
        <div class="alert alert-success" role="alert">
            <p>[質問]<br>{{object.question | linebreaksbr}}</p>
            <p>[回答]<br>{{object.answer | linebreaksbr}}</p>
            <p>[企業名]{{object.company}}</p>
            <p>[状況]{{object.state}}</p>
            <p>[文字数]{{object.char_num}}</p>
            <p>[公開状況]{{object.get_open_info_display}}</p>


        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/history/list.html
{% extends 'base.html' %}

{% block header %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">ES質問まとめアプリ</h1>
        <p class="lead">自分の回答をまとめて管理！</p>
        <a href="{% url 'create_his'%}" class="btn btn-warning btn-lg" tabindex="-1" role="button"
            aria-disabled="true">質問と回答を追加</a>
        <a href="{% url 'create_tag'%}" class="btn btn-success btn-lg" tabindex="-1" role="button"
            aria-disabled="true">タグを追加</a>
    </div>
</div>
{% endblock header %}

{% block content %}


<div class="container">
    {% for item in histories %}
    <div class="alert alert-success" role="alert">

        {% if item.open_info == 'private' %}
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-lock-fill" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M2.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z" />
            <path fill-rule="evenodd" d="M4.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z" />
        </svg>
        {% else %}
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-unlock-fill" fill="currentColor"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M.5 9a2 2 0 0 1 2-2h7a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-7a2 2 0 0 1-2-2V9z" />
            <path fill-rule="evenodd" d="M8.5 4a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z" />
        </svg>
        {% endif %}

        <p>[質問]{{item.question}}</p>

        {% for tag in item.tags.all %}
        <a href="#" class="btn btn-dark btn" tabindex="-1" role="button" aria-disabled="true">{{tag}}</a>
        {% endfor %}
        <br>
        <br>
        <a href="{% url 'detail_his' item.pk %}" class="btn btn-info btn" tabindex="-1" role="button"
            aria-disabled="true">詳細</a>
        <a href="{% url 'update' item.pk %}" class="btn btn-primary btn" tabindex="-1" role="button"
            aria-disabled="true">編集</a>
        <a href="{% url 'delete' item.pk %}" class="btn btn-danger btn" tabindex="-1" role="button"
            aria-disabled="true">削除</a>
    </div>

    {% endfor %}
</div>

{% endblock content %}

templates/history/list_not_exist.html
{% extends 'base.html' %}
{% block header %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>{{username}}さんは存在していません．</h1>
    </div>
</div>

{% endblock header %}

templates/history/list_not_login.html
{% extends 'base.html' %}

{% block header %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1>{{username}}さんの回答です．</h1>
    </div>
</div>

{% endblock header %}

{% block content %}
<div class="container">
    {% for item in histories %}
    <div class="alert alert-success" role="alert">
        <p>[質問]<br>{{item.question | linebreaksbr}}</p>
        <p>[回答]<br>{{item.answer | linebreaksbr}}</p>

        {% for tag in item.tags.all %}
        <a href="#" class="btn btn-dark btn" tabindex="-1" role="button" aria-disabled="true">{{tag}}</a>
        {% endfor %}
    </div>

    {% endfor %}
</div>

{% endblock content %}

templates/history/login.html
<!doctype html>
{% load static %}
<html lang="ja">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <link rel="stylesheet" type="text/css" href="{% static 'history/style.css' %}">

    <title>ES質問まとめアプリ</title>
</head>

<body>

    <div class="container">
        <form class="form-signin" method="POST" action="">{% csrf_token %}
            <!-- <img class="mb-4" src="../../assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"> -->

            <h1 class="h3 mb-3 font-weight-normal">ログイン</h1>


            <label for="inputEmail" class="sr-only">ユーザー名</label>
            <input type="text" id="inputEmail" class="form-control" name="username" placeholder="ユーザー名" required
                autofocus>
            <label for="inputPassword" class="sr-only">パスワード</label>
            <input type="password" id="inputPassword" class="form-control" name="password" placeholder="パスワード" required>
            <div class="checkbox mb-3">

            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">ログイン</button>
            <p>新規登録は<a href="{% url 'signup'%}">こちら</a>から</p>
        </form>



        <form class="form-signin" method="GET" , action="{% url 'search_user' %}">{% csrf_token %}
            <h1 class="h3 mb-3 font-weight-normal"></h1>
            <h2 class="h4 mb-4 font-weight-normal">ゲストユーザとして<br>他人のプロフィールを閲覧</h2>
            <input class="form-control mr-sm-2" type="search" placeholder="ユーザー検索" aria-label="Search"
                name="search_username">
            <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">検索</button>
        </form>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script>
        window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
    <script src="/docs/4.5/assets/js/vendor/anchor.min.js"></script>
    <script src="/docs/4.5/assets/js/vendor/clipboard.min.js"></script>
    <script src="/docs/4.5/assets/js/vendor/bs-custom-file-input.min.js"></script>
    <script src="/docs/4.5/assets/js/src/application.js"></script>
    <script src="/docs/4.5/assets/js/src/search.js"></script>
    <script src="/docs/4.5/assets/js/src/ie-emulation-modes-warning.js"></script>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/history/update_post.html
{% extends 'base.html' %}


{% block header %}
<div class="alert alert-secondary" role="alert">
    <div class="container">
        <p class="display-4">修正</p>
    </div>
</div>

{% endblock header %}


{% block content %}
<div class="container">
    <form action="" , method="POST">
        {% csrf_token %}
        <p>質問</p>
        <p>{{form.question}}</p>
        <p>回答</p>
        <p>{{form.answer}}</p>
        <p>タグ(複数選択できます(ctrlまたはcmmd+クリック))</p>

        {% if len_tags == 0 %}
        <div class="box">
            <p>タグはまだありません</p>
        </div>

        {% else %}
        <p><label for="id_tags"></label> <select size="{{len_tags}}" name="tags" id="id_tags" multiple>

                {% for tag in tags %}
                <option value="{{tag.pk}}">{{tag.tag_name}}</option>
                {% endfor %}

            </select></p>
        {% endif %}
        <p>企業名{{form.company}}</p>
        <p>イベント{{form.state}}</p>
        <p>公開{{form.open_info}}</p>

        <input type="submit" value="更新する">
    </form>
</div>

{% endblock content %}